apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
spec:
  containers:
  - name: pg
    imagePullPolicy: Never  
    image: pg:v0
    env:
      - name: POSTGRES_PASSWORD
        value: "mysecretpassword"
    ports:
      - containerPort: 5432
        name: pg

---
apiVersion: v1
kind: Service
metadata:
  name: pg-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: postgres
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: pg
